version: "3.3"
services:
  db:
    image: postgres:13.3
    environment:
      # (default) user: psotgres, database: postgres
      POSTGRES_PASSWORD: postgres
    restart: "no"
    ports:
      - 5432:5432
